package com.channelape.completedtasks.reports.data.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = DataBusiness.TABLE_NAME)
public class DataBusiness {

	public static final String TABLE_NAME = "Businesses";

	private static final String ID = "id";
	private static final String NAME = "name";
	private static final String TIME_ZONE = "timeZone";
	private static final String ALPHABETIC_CURRENCY_CODE = "alphabeticCurrencyCode";
	private static final String INVENTORY_ITEM_KEY = "inventoryItemKey";

	private String id;
	private String name;
	private String timeZone;
	private String alphabeticCurrencyCode;
	private String inventoryItemKey;

	@DynamoDBHashKey(attributeName = ID)
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = NAME)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName = TIME_ZONE)
	public String getTimeZone() {
		return timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	@DynamoDBAttribute(attributeName = ALPHABETIC_CURRENCY_CODE)
	public String getAlphabeticCurrencyCode() {
		return alphabeticCurrencyCode;
	}

	public void setAlphabeticCurrencyCode(String alphabeticCurrencyCode) {
		this.alphabeticCurrencyCode = alphabeticCurrencyCode.toUpperCase();
	}

	@DynamoDBAttribute(attributeName = INVENTORY_ITEM_KEY)
	public String getInventoryItemKey() {
		return inventoryItemKey;
	}

	public void setInventoryItemKey(String inventoryItemKey) {
		this.inventoryItemKey = inventoryItemKey.toUpperCase();
	}

}
