package com.channelape.completedtasks.reports.data.models;

import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = DataIntegration.TABLE_NAME)
public class DataIntegration {

	public static final String TABLE_NAME = "Integrations";

	private static final String ID = "id";
	private static final String NAME = "name";
	private static final String TYPE = "type";
	private static final String ACTIONS = "actions";
	private static final String IS_PUBLIC = "isPublic";
	private static final String CREATION_TIME = "creationTime";
	private static final String UPDATE_TIME = "updateTime";

	private String id;
	private String name;
	private String type;
	private Map<String, String> actions;
	private boolean isPublic;
	private long creationTimeInMilliseconds;
	private long updateTimeInMilliseconds;

	@DynamoDBHashKey(attributeName = ID)
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = NAME)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName = TYPE)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@DynamoDBAttribute(attributeName = ACTIONS)
	public Map<String, String> getActions() {
		return actions;
	}

	public void setActions(Map<String, String> actions) {
		this.actions = actions;
	}

	@DynamoDBAttribute(attributeName = IS_PUBLIC)
	public boolean isPublic() {
		return isPublic;
	}

	public void setPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}

	@DynamoDBAttribute(attributeName = CREATION_TIME)
	public long getCreationTimeInMilliseconds() {
		return creationTimeInMilliseconds;
	}

	public void setCreationTimeInMilliseconds(long creationTimeInMilliseconds) {
		this.creationTimeInMilliseconds = creationTimeInMilliseconds;
	}

	@DynamoDBAttribute(attributeName = UPDATE_TIME)
	public long getUpdateTimeInMilliseconds() {
		return updateTimeInMilliseconds;
	}

	public void setUpdateTimeInMilliseconds(long updateTimeInMilliseconds) {
		this.updateTimeInMilliseconds = updateTimeInMilliseconds;
	}

}
